[package]
name = "input-rust"
description = "A Rust crate for prompting user input, similar to Python's input(), with error handling."
version = "1.0.0"
edition = "2024"
authors = ["Saikat Das <sd.saikat369@gmail.com>"]
license = "MIT"

[dependencies]
